inherit_from: .rubocop_todo.yml

AllCops:
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - Gemfile
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false