inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  # 除外
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - Gemfile
    - 'vendor/**/*'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/cooking_informations_controller.rb'
    - 'app/controllers/password_resets_controller.rb'
    - 'app/forms/calculate_cooking_time.rb'

MethodLength:
  Exclude:
    - 'app/controllers/cooking_informations_controller.rb'
    - 'app/controllers/password_resets_controller.rb'
    - 'app/forms/calculate_cooking_time.rb'


Style/StringConcatenation:
  Mode: conservative

CyclomaticComplexity:
  Exclude:
    - 'app/forms/calculate_cooking_time.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/forms/calculate_cooking_time.rb'
